In [15]:
from math import sqrt
from numpy import diag
from scipy.linalg import svd

In [16]:
from numpy import dot
from numpy import array
B = array([[0, 1, 1], [sqrt(2),2 , 0], [0,1, 1]])
print(B)
V, d, VT = svd(B)

Sigma = diag(d)
B = V.dot(Sigma.dot(VT))

print(V)
print(B)
print(VT)

[[0.         1.         1.        ]
 [1.41421356 2.         0.        ]
 [0.         1.         1.        ]]
[[-0.40824829  0.57735027 -0.70710678]
 [-0.81649658 -0.57735027  0.        ]
 [-0.40824829  0.57735027  0.70710678]]
[[-2.08237690e-16  1.00000000e+00  1.00000000e+00]
 [ 1.41421356e+00  2.00000000e+00 -1.22305252e-16]
 [-1.35701937e-16  1.00000000e+00  1.00000000e+00]]
[[-4.08248290e-01 -8.66025404e-01 -2.88675135e-01]
 [-5.77350269e-01 -4.89172797e-17  8.16496581e-01]
 [-7.07106781e-01  5.00000000e-01 -5.00000000e-01]]
